---
# tasks file

- name: Deploy amersports servers
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ deploy_from }}"
    ansistrano_deploy_to: "{{ deploy_to }}"
    ansistrano_keep_releases: "{{ keep_releases }}"
    ansistrano_shared_paths:
      - "var"
      - "media"
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/my-after-update-code-tasks.yml"
    lavoweb_remove_sufix: "{{ deploy_environment }}"
  pre_tasks:
    - name: include vars
      include_vars: vars/{{ deploy_environment }}.yml
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }